FROM --platform=linux/arm64 arm64v8/nginx
COPY ./server/public /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY admin.conf /etc/nginx/conf.d

#fire up nginx
EXPOSE 80
CMD ["nginx","-g","daemon off;"]