version: '3'
services:
  # client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   ports:
  #     - 5174:5174
  # mysql:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.mysql
  #   ports:
  #     - 3307:3307
  #   networks:
  #     - umbrella
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.server
  #   ports:
  #     - 3030:3030
  #   # depends_on:
  #   #   - mysql
  #   networks:
  #     - umbrella
  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    ports:
      - 80:80
    networks:
      - umbrella

networks:
  umbrella:
