# Specify the base image
FROM node:16-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if using npm)
COPY ./client/package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY ./client .

# Expose the port the server will listen on
EXPOSE 5174

# Set the command to run when the container starts
CMD ["npm","run","serve"]
