Resources:
  MyECSCluster:
    Type: AWS::ECS::Cluster

  MyTaskDefinitionNginx:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: nginx-container
          Image: <YOUR_ECR_REPOSITORY_URI>/nginx-image:latest
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
          Memory: 512
          Cpu: 256

  MyTaskDefinitionNodeJS:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: nodejs-container
          Image: <YOUR_ECR_REPOSITORY_URI>/nodejs-image:latest
          PortMappings:
            - ContainerPort: 3000
              HostPort: 3000
          Memory: 512
          Cpu: 256
          Environment:
            - Name: NODE_ENV
              Value: production

  MyECSServiceNginx:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyECSCluster
      TaskDefinition: !Ref MyTaskDefinitionNginx
      DesiredCount: 1

  MyECSServiceNodeJS:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyECSCluster
      TaskDefinition: !Ref MyTaskDefinitionNodeJS
      DesiredCount: 1
